services:
  postgres:
    image: postgres:latest
    container_name: sentinel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: SentinelDB
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sentinel-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest