services:
  sentinel-db:
    image: postgres:latest
    container_name: sentinel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: SentinelDB
    ports:
      - "5432:5432"

  sentinel-broker:
    image: rabbitmq:3-management
    container_name: sentinel-broker
    ports:
      - "5672:5672"
      - "15672:15672"

  alert-api:
    build:
      context: .
      dockerfile: Alert.API/Dockerfile
    container_name: alert-api
    depends_on:
      - sentinel-db
      - sentinel-broker
    ports:
      - "5000:8080"

  notification-service:
    build:
      context: .
      dockerfile: Notification.Service/Dockerfile
    container_name: notification-service
    depends_on:
      - sentinel-broker